diera/diera/urls.py
from cms.sitemaps import CMSSitemap
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path

admin.autodiscover()

urlpatterns = [
    path("sitemap.xml", sitemap, {"sitemaps": {"cmspages": CMSSitemap}}),
]

urlpatterns += [
    path("photologue/", include("photologue.urls", namespace="photologue"))
]

urlpatterns += i18n_patterns(path("admin/", admin.site.urls), path("", include("cms.urls")), prefix_default_language=False)

# This is only needed when using runserver.
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

diera/event_calendar/urls.py
from django.urls import path

from . import views

app_name = 'event_calendar'

urlpatterns = [
    path('', views.event_calendar, name='calendar'),
    path('<int:year>/<int:month>/', views.event_calendar, name='calendar')
]

diera/event_calendar/forms.py
from django import forms
from django.db import models
from django.utils.translation import gettext_lazy as _

from . import queries

class CalendarNavigationForm(forms.Form):
    class Months(models.TextChoices):
        JANUARY = 1, _('January')
        FEBRUARY = 2, _('February')
        MARCH = 3, _('March')
        APRIL = 4, _('April')
        MAY = 5, _('May')
        JUNE = 6, _('June')
        JULY = 7, _('July')
        AUGUST = 8, _('August')
        SEPTEMBER = 9, _('September')
        OCTOBER = 10, _('October')
        NOVEMBER = 11, _('November')
        DECEMBER = 12, _('December')

    month = forms.ChoiceField(label='Month', choices=Months.choices)
    year = forms.ChoiceField(label='Year', choices=queries.get_years_with_published_events_as_choices())

diera/event_calendar/views.py
from datetime import date

from django.http import HttpResponseRedirect
import logging

from django.shortcuts import render

from .forms import CalendarNavigationForm

# logger = logging.getLogger(__name__)

def event_calendar(request, year=date.today().year, month=date.today().month):
    """Show calendar"""

    # LOGGING year and month for debug purposes
    # logger.info(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>.Sample message")

    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a from instance and populate it with data from the request
        calNavForm = CalendarNavigationForm(request.POST)
        # check wether the form is valid:
        if calNavForm.is_valid():
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
            year = calNavForm.cleaned_data['year']
            month = calNavForm.cleaned_data['month']

            # render the calendar for submitted year and month
            return render(request, 'event_calendar/calendar.html', {'year': int(year), 'month': int(month), 'calNavForm': calNavForm})

    # if a GET (or any other method) we'll create a blank form
    else:
        # Initialize form with current year and month
        calNavForm = CalendarNavigationForm(initial={'month':month, 'year': year})

    return render(request, 'event_calendar/calendar.html', {'year': int(year), 'month': int(month), 'calNavForm': calNavForm})

diera/event_calendar/templates/event_calendar/includes/calendar.html
{% load i18n %}
{% load cms_tags menu_tags %}
{% load thumbnail %}
{% load calendar_tags %}

{% if eteasers_for_month.upcoming_eteasers|length > 0 %}

<!-- Calendar navigation form -->
<div id="calendar-nav">
    <form class="row" action="{% url 'event_calendar:calendar' %}" method="post">
        {% csrf_token %}

        <div id="year-select-container" class="col-4">
            {{ calNavForm.month }}
        </div>

        <div id="month-select-container" class="col-4">
            {{ calNavForm.year }}
        </div>

        <div id="submit-container" class="col-4">
            <input id="show-program-button" type="submit" value="{% translate 'Show' %}">
        </div>
    </form>
</div>


<div id="calendar-container">

    <!-- DAYS GRID -->
    <!-- Iterate through weeks of the month -->
    {% for eteasers_for_week in eteasers_for_month %}
    <div class="row"> <!-- A row represents a week -->

        <!-- Iterate through days of the week -->
        {% for eteasers_for_day in eteasers_for_week %}
        <div class="col day"> <!-- A column represents a day -->

            {% if eteasers_for_day.0 == 0 %}  <!-- Day is not a part of the month -->
            <div class="square" style="display:none;">  <!-- Do not display days outside of month -->
                <div class="content"></div>
            </div>

            {% elif eteasers_for_day.1|length == 0 %}  <!-- Day is a part of the month, but without scheduled events -->

            {% now "d" as current_day %}
            {% now "m" as current_month %}

            <!-- Highlight current days without scheduled events -->
            {% if current_day == eteasers_for_day.0|slugify and current_month == program_date|date:"m"|slugify %}
            <div class="square" style="background-color:black;">
                <div class="content" style="color:white">
                    {{ eteasers_for_day.0 }}
                </div>
            </div>
            {% else %}
            <div class="square" style="">
                <div class="content">
                    {{ eteasers_for_day.0 }}
                </div>
            </div>
            {% endif %}

            {% elif eteasers_for_day.1|length == 1 %}  <!-- One event is scheduled for the day -->
            <div class="square">
                <div class="content">

                    {% with eteaser=eteasers_for_day.1.0 %}  <!-- Select the teaser -->
                    <a class="event-anchor" href="{{ eteaser.event_url }}">

                        {% thumbnail eteaser.image 400x430 crop upscale as eteaser_image %}
                        {% thumbnail eteaser.image 600x300 crop upscale as eteaser_image_pop %}
                        <img class="teaser-image"
                             id="thumb-{{ eteasers_for_day.0 }}-0"
                             src="{{ eteaser_image.url }}"
                             title="{{ eteaser.event_title|upper }}"
                             data-trigger="hover"
                             data-toggle="popover"
                             data-template='<div class="popover" role="tooltip"><div class="row popover-date"><div class="col popover-day">{{ eteaser.date_from|date:"j. n." }}</div><div class="col popover-time">{{ eteaser.date_from|date:"H:i" }}</div></div><img src="{{ eteaser_image_pop.url }}"/><h3 class="popover-header"></h3><div class="pop-body">{% show_placeholder "genre" eteaser.page_id %}</div></div>'
                        />
                    </a>
                    {% endwith %}

                </div>
            </div>

            {% else %}  <!-- There are multiple events scheduled for the day -->
            <div class="square">
                <div class="content">

                    <!-- Multiple events are shown in carousel -->
                    <div id="carousel-{{ eteasers_for_day.0 }}" class="carousel slide carousel-fade" data-ride="carousel" data-interval="false">
                        <div class="carousel-inner">

                            <!-- Indicators -->
                            <ol class="carousel-indicators">

                                <!-- Iterate through event teasers for the day and generate carousel indicators -->
                                {% for eteaser in eteasers_for_day.1 %}

                                {% if forloop.counter0 == 0 %}
                                <li data-target="#carousel-{{ eteasers_for_day.0 }}" data-slide-to="{{ forloop.counter0 }}" class="active"></li>
                                {% else %}
                                <li data-target="#carousel-{{ eteasers_for_day.0 }}" data-slide-to="{{ forloop.counter0 }}"></li>
                                {% endif %}

                                {% endfor %}

                            </ol>

                            <!-- Iterate through event teasers for the day and generate carousel slides -->
                            {% for eteaser in eteasers_for_day.1 %}

                            {% if forloop.counter0 == 0 %}  <!-- First slide -->
                            <div class="carousel-item active">
                                <a class="event-anchor" href="{{ eteaser.event_url }}">

                                    <div class="teaser-image">
                                        {% thumbnail eteaser.image 400x430 crop upscale as eteaser_image %}
                                        {% thumbnail eteaser.image 600x300 crop upscale as eteaser_image_pop %}
                                        <img class="teaser-image"
                                            id="thumb-{{ eteasers_for_day.0 }}-0"
                                            src="{{ eteaser_image.url }}"
                                            title="{{ eteaser.event_title|upper }}"
                                            data-trigger="hover"
                                            data-toggle="popover"
                                            data-template='<div class="popover" role="tooltip"><div class="row popover-date"><div class="col popover-day">{{ eteaser.date_from|date:"j. n." }}</div><div class="col popover-time">{{ eteaser.date_from|date:"H:i" }}</div></div><img src="{{ eteaser_image_pop.url }}"/><h3 class="popover-header"></h3><div class="pop-body">{% show_placeholder "genre" eteaser.page_id %}</div></div>'
                                        />
                                    </div>

                                </a>
                            </div>

                            {% else %}  <!-- Rest of slides -->
                            <div class="carousel-item">
                                <a class="event-anchor" href="{{ eteaser.event_url }}">

                                    <div class="teaser-image">
                                        {% thumbnail eteaser.image 400x430 crop upscale as eteaser_image %}
                                        {% thumbnail eteaser.image 600x300 crop upscale as eteaser_image_pop %}
                                        <img class="teaser-image"
                                             id="thumb-{{ eteasers_for_day.0 }}-0"
                                             src="{{ eteaser_image.url }}"
                                             title="{{ eteaser.event_title|upper }}"
                                             data-trigger="hover"
                                             data-toggle="popover"
                                             data-template='<div class="popover" role="tooltip"><div class="row popover-date"><div class="col popover-day">{{ eteaser.date_from|date:"j. n." }}</div><div class="col popover-time">{{ eteaser.date_from|date:"H:i" }}</div></div><img src="{{ eteaser_image_pop.url }}"/><h3 class="popover-header"></h3><div class="pop-body">{% show_placeholder "genre" eteaser.page_id %}</div></div>'
                                        />
                                    </div>

                                </a>
                            </div>
                            {% endif %}

                            {% endfor %}  <!-- Close tag for iterating through events of the day -->

                        </div>

                        <!-- Carousel controls -->
                        <a class="carousel-control-prev" href="#carousel-{{ eteasers_for_day.0 }}" role="button" data-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span class="sr-only">Previous</span>
                        </a>
                        <a class="carousel-control-next" href="#carousel-{{ eteasers_for_day.0 }}" role="button" data-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                            <span class="sr-only">Next</span>
                        </a>
                    </div>  <!-- Close carousel -->
                </div>  <!-- Closes calendar content cell -->
            </div>  <!-- Close the square -->

            {% endif %} <!-- Close no/single/multiple events branching -->

        </div> <!-- Close column branching -->
        {% endfor %}  <!-- Close the tag for iterating through days of the week -->

    </div>
    {% endfor %}  <!-- Close the tag for iterating through weeks of the month -->
</div>

<!-- CALENDAR FOR SMALLER DISPLAYS -->
<div id="calendar-sm" style="display:none">

    {% for eteaser_pair in eteasers_for_month.upcoming_eteasers %}

    <div class="card-group">

        {% for eteaser in eteaser_pair %}

        <div class="card eteaser-card-sm" style="border: 2px solid black;">

            <!-- EVENT SCHEDULING -->
            <div class="eteaser-sm-schedule">
                <div class="row">
                    <div class="col">
                        {{ eteaser.date_from|date:"j.m." }}
                    </div>
                    <div class="col" style="text-align:right;">
                        {{ eteaser.date_from|date:"H:i" }}
                    </div>
                </div>
            </div>

            <!-- EVENT TEASER IMAGE -->
            {% if eteaser.image %}
            {% thumbnail eteaser.image 600x300 crop upscale as cropped_eteaser_image %}
            <a href="{{ eteaser.event_url }}">
                <img class="" style="border-top:2px solid black; border-bottom:2px solid black" src="{{ cropped_eteaser_image.url }}">
            </a>
            {% endif %}

            <!-- EVENT TITLE -->
            <div class="eteaser-sm-title">
                <a href="{{ eteaser.event_url }}">
                    {{ eteaser.event_title|upper }}
                </a>
            </div>

            <!-- EVENT GENRE -->
            <div class="eteaser-sm-genre">
                {% show_placeholder "genre" eteaser.page_id %}
            </div>

        </div>
        {% endfor %}
    </div>
    {% endfor %}

</div>  <!-- ENDING TAG FOR CONTAINER FOR MASONRY -->

{% else %}  <!-- Show infographics, if selected month is without programming -->

<div id="infographics-container">
    <!-- Calendar navigation form -->
    <div id="calendar-nav-sm">
        <form action="{% url 'event_calendar:calendar' %}" method="post">
            {% csrf_token %}
            <div class="row">

                <div id="month-select-container-sm" class="col-4">
                    {{ calNavForm.month }}
                </div>

                <div id="year-select-container-sm" class="col-4">
                    {{ calNavForm.year }}
                </div>

                <div id="submit-container-sm" class="col-4">
                    <input id="show-program-button" type="submit" value="{% translate 'Show' %}">
                </div>
            </div>
        </form>
    </div>

    <img src="{% get_random_infographics_url program_date.year program_date.month %}" >
</div>

{% endif %}

diera/event_calendar/templates/event_calendar/includes/calendar_BACKUP.html
{% load i18n %}
{% load thumbnail %}

<div class="container">

    <!-- MONTH SLIDER -->
    <div class="row">
        <div class="col month">
            <div>
                <a href="{% url 'event_calendar:calendar' previous_date.year previous_date.month %}"><i class="fas fa-angle-left"></i></a>
                <b>{{ current_date|date:"E"|upper }}</b>
                <a href="{% url 'event_calendar:calendar' next_date.year next_date.month %}"><i class="fas fa-angle-right"></i></a>
            </div>
        </div>
    </div>

    <!-- DAYS GRID -->
    <!-- Iterate through weeks of the month -->
    {% for eteasers_for_week in eteasers_for_month %}
    <div class="row"> <!-- A row represents a week -->

        <!-- Iterate through days of the week -->
        {% for eteasers_for_day in eteasers_for_week %}
        <div class="col day"> <!-- A column represents a day -->

            {% if eteasers_for_day.0 == 0 %}  <!-- Day is not a part of the month -->
            <div class="square">
                <div class="content"></div>
            </div>

            {% elif eteasers_for_day.1|length == 0 %}  <!-- Day is a part of the month but without scheduled events -->
            <div class="square">
                <div class="content">
                    {{ eteasers_for_day.0 }}
                </div>
            </div>

            {% elif eteasers_for_day.1|length == 1 %}  <!-- One event is scheduled for the day -->
            <div class="square">
                <div class="content">

                    {% with eteaser=eteasers_for_day.1.0 %}  <!-- Select the teaser -->
                    <a class="event-anchor" href="{{ eteaser.event_url }}">

                        <!-- {% thumbnail eteaser.image "400x400" crop="center" as teaser_image %} -->
                        <!-- {% thumbnail eteaser.image "300x150" crop="center" as teaser_image_pop %} -->
                        <!-- <img class="teaser-image"
                             id="thumb-{{ eteasers_for_day.0 }}-0"
                             src="{{ teaser_image.url }}"
                             title="{{ eteaser.event_title|upper }}"
                             data-trigger="hover"
                             data-content="{{ eteaser.text|striptags|upper }}"
                             data-toggle="popover"
                             data-template='<div class="popover" role="tooltip"><div class="row popover-date"><div class="col popover-day">{{ eteaser.date_from|date:"j. n." }}</div><div class="col popover-time">{{ eteaser.date_from|date:"H:i" }}</div></div><img src="{{ teaser_image_pop.url }}"/><h3 class="popover-header"></h3><div class="popover-body"></div></div>'
                             /> -->
                        <!-- {% endthumbnail %} -->
                        <!-- {% endthumbnail %} -->

                    </a>
                    {% endwith %}

                </div>
            </div>

            {% else %}  <!-- There are multiple events scheduled for the day -->
            <div class="square">
                <div class="content">

                    <!-- Multiple events are shown in carousel -->
                    <div id="carousel-{{ eteasers_for_day.0 }}" class="carousel slide carousel-fade" data-ride="carousel" data-interval="false">
                        <div class="carousel-inner">

                            <!-- Indicators -->
                            <ol class="carousel-indicators">

                                <!-- Iterate through event teasers for the day and generate carousel indicators -->
                                {% for eteaser in eteasers_for_day.1 %}

                                {% if forloop.counter0 == 0 %}
                                <li data-target="#carousel-{{ eteasers_for_day.0 }}" data-slide-to="{{ forloop.counter0 }}" class="active"></li>
                                {% else %}
                                <li data-target="#carousel-{{ eteasers_for_day.0 }}" data-slide-to="{{ forloop.counter0 }}"></li>
                                {% endif %}

                                {% endfor %}

                            </ol>

                            <!-- Iterate through event teasers for the day and generate carousel slides -->
                            {% for eteaser in eteasers_for_day.1 %}

                            {% if forloop.counter0 == 0 %}  <!-- First slide -->
                            <div class="carousel-item active">
                                <a class="event-anchor" href="{{ eteaser.event_url }}">

                                    {% thumbnail eteaser.image "400x400" crop="center" as teaser_image %}
                                    {% thumbnail eteaser.image "300x150" crop="center" as teaser_image_pop %}
                                    <img class="teaser-image"
                                         src="{{ teaser_image.url }}"
                                         title="{{ eteaser.event_title|upper }}"
                                         data-toggle="popover"
                                         data-trigger="hover"
                                         data-content="{{ eteaser.text|striptags|upper }}"
                                         data-template='<div class="popover" role="tooltip"><div class="row popover-date"><div class="col popover-day">{{ eteaser.date_from|date:"j. n." }}</div><div class="col popover-time">{{ eteaser.date_from|date:"H:i" }}</div></div><img src="{{ teaser_image_pop.url }}"/><h3 class="popover-header"></h3><div class="popover-body"></div></div>'
                                    />
                                    {% endthumbnail %}
                                    {% endthumbnail %}

                                </a>
                            </div>

                            {% else %}  <!-- Rest of slides -->
                            <div class="carousel-item">
                                <a class="event-anchor" href="{{ eteaser.event_url }}">

                                    {% thumbnail eteaser.image "400x400" crop="center" as teaser_image %}
                                    {% thumbnail eteaser.image "300x150" crop="center" as teaser_image_pop %}
                                    <img class="teaser-image"
                                         src="{{ teaser_image.url }}"
                                         title="{{ eteaser.event_title|upper }}"
                                         data-toggle="popover"
                                         data-trigger="hover"
                                         data-content="{{ eteaser.text|striptags|upper }}"
                                         data-template='<div class="popover" role="tooltip"><div class="row popover-date"><div class="col popover-day">{{ eteaser.date_from|date:"j. n." }}</div><div class="col popover-time">{{ eteaser.date_from|date:"H:i" }}</div></div><img src="{{ teaser_image_pop.url }}"/><h3 class="popover-header"></h3><div class="popover-body"></div></div>'
                                    />
                                    {% endthumbnail %}
                                    {% endthumbnail %}

                                </a>
                            </div>
                            {% endif %}

                            {% endfor %}  <!-- Close tag for iterating through events of the day -->

                        </div>

                        <!-- Carousel controls -->
                        <a class="carousel-control-prev" href="#carousel-{{ eteasers_for_day.0 }}" role="button" data-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span class="sr-only">Previous</span>
                        </a>
                        <a class="carousel-control-next" href="#carousel-{{ eteasers_for_day.0 }}" role="button" data-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                            <span class="sr-only">Next</span>
                        </a>
                    </div>  <!-- Close carousel -->
                </div>  <!-- Closes calendar content cell -->
            </div>  <!-- Close the square -->

            {% endif %} <!-- Close no/single/multiple events branching -->

        </div> <!-- Close column branching -->
        {% endfor %}  <!-- Close the tag for iterating through days of the week -->

    </div>
    {% endfor %}  <!-- Close the tag for iterating through weeks of the month -->

</div>

<script>
 /* Initialize all popovers */
 $(function () {
     $('.teaser-image').popover();
 })
</script>

diera/event_calendar/templates/event_calendar/includes/upcoming_events.html
{% load i18n %}
{% load cms_tags menu_tags %}
{% load thumbnail %}
{% load calendar_tags %}

<div class="row g-1">

  {% for eteaser in eteasers %}

  <div class="col-12 col-md-6 col-lg-4">
    <a href="{{ eteaser.event_url }}" class="upcoming-eteaser">
      <div class="card h-100 p-2 pb-0">
        {% thumbnail eteaser.image 600x300 crop upscale as eteaser_image %}
        <img class="card-img-top" src="{{ eteaser_image.url }}">
        <div class="card-body p-0 mt-2">
          <h2 class="card-title fs-1 lh-1 text-uppercase">{{ eteaser.event_title }}</h2>
          <h3 class="card-subtitle mt-2 fs-3">
            {% show_placeholder "genre" eteaser.page_id %}
          </h3>
        </div>
        <div class="card-footer p-0">
          <div class="row pt-1 pb-1">
            <div class="col-9 fs-3 text-uppercase">{{ eteaser.date_from|date:"j.n." }} <span class="">{% get_hr_time_span eteaser.date_from %}</span></div>
            <div class="col-3 fs-3 text-end">{{ eteaser.date_from|date:"H:i" }}</div>
          </div>
        </div>
      </div>
    </a>
  </div>
  {% endfor %}

</div>

diera/event_calendar/templates/event_calendar/includes/upcoming_events_BACKUP.html
<div class="px-4">
    <div class="row" data-masonry='{"percentPosition": true }'>
        {% for eteaser in eteasers %}
        <div class="col-sm6 col-lg-4 mb-4">
            <div class="card mb-3" >
                <div class="card-header">
                    <div class="row g-0">
                        <div class="col-md-4">
                            <span>{{ eteaser.date_from|date:"j M." }}</span>
                        </div>
                        <div class="col-md-8" style="text-align:right;">
                            <span>{{ eteaser.date_from|date:"H:i / l" }}</span>
                        </div>
                        <div class="col-md-1">
                        </div>
                    </div>
                </div>
                <div class="row g-0">
                    <div class="col-md-3 g-0 eteaser-image">
                        <img src="{{ eteaser.image_url }}">
                    </div>
                    <div class="col-md-9 g-0">
                        <div class="card-body">
                            <a href="{{ eteaser.event_url }}">
                                <h4 class="card-title">{{ eteaser.event_title }}</h4>
                            </a>
                            {{ eteaser.text }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

diera/event_calendar/templates/event_calendar/includes/upcoming_events_BACKUP1.html
<div class="col-sm6 col-lg-6 mb-4">
    <div class="card">
        <div class="card-header text-white">
            Upcoming Events
        </div>
        <div class="card-body feature-teaser-body">
            <div class="card-text">
                {% for eteaser in etasers %}
                <h4>{{ eteaser.event_title }}</h4>
                {% endfor %}
            </div>
        </div>
        <div class="card-footer">
            <a href="">More</a>
        </div>
    </div>
</div>

diera/event_calendar/templates/event_calendar/includes/upcoming_events_BACKUP2.html
<div class="col-sm6 col-lg-6 mb-4">
    <div class="card">
        <div class="card-header text-white">
            Upcoming Events
        </div>
        <div class="card-body feature-teaser-body">
            <div class="card-text">
                {% for eteaser in eteasers %}
                <div class="card mb-3" >
                    <div class="card-header">
                        <div class="row g-0">
                            <div class="col-md-4">
                                <span>{{ eteaser.date_from|date:"j M." }}</span>
                            </div>
                            <div class="col-md-8" style="text-align:right;">
                                <span>{{ eteaser.date_from|date:"H:i / l" }}</span>
                            </div>
                            <div class="col-md-1">
                            </div>
                        </div>
                    </div>
                    <div class="row g-0">
                        <div class="col-md-3 g-0 eteaser-image">
                            <img src="{{ eteaser.image_url }}">
                        </div>
                        <div class="col-md-9 g-0">
                            <div class="card-body">
                                <a href="{{ eteaser.event_url }}">
                                    <h4 class="card-title">{{ eteaser.event_title }}</h4>
                                </a>
                                {{ eteaser.text }}
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
        <div class="card-footer">
            <a href="">More</a>
        </div>
    </div>
</div>