diera/archive/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from . import views

app_name = 'archive'

urlpatterns = [
    path('', views.IndexList.as_view(), name='index'),
]

htmx_urlpatterns = [
    path("fotky/page<int:page>/", views.GalleryList.as_view(), name="photos"),
    path("fotky/<int:year>/page<int:page>/", views.GalleryList.as_view(), name="photos"),
    path("fotky/<int:year>/<int:month>/page<int:page>/", views.GalleryList.as_view(), name="photos"),
    path("galeria/<int:gallery>/page<int:page>/", views.PhotoList.as_view(), name="gallery"),
    path("program/page<int:page>/", views.EventList.as_view(), name="programming"),
    path("video/page<int:page>/", views.VideoList.as_view(), name="video"),
    path("audio/page<int:page>/", views.AudioList.as_view(), name="audio"),
    path("search-results/", views.SearchResults.as_view(), name="search-results"),
    path("search-results/page<int:page>/", views.SearchResults.as_view(), name="search-results"),
    path("search-results/page<int:page>/query<query>/", views.SearchResults.as_view(), name="search-results")
]

urlpatterns += htmx_urlpatterns

diera/diera/urls.py
from cms.sitemaps import CMSSitemap
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path

admin.autodiscover()

urlpatterns = [
    path("sitemap.xml", sitemap, {"sitemaps": {"cmspages": CMSSitemap}}),
]

urlpatterns += [
    path("photologue/", include("photologue.urls", namespace="photologue"))
]

urlpatterns += i18n_patterns(path("admin/", admin.site.urls), path("", include("cms.urls")), prefix_default_language=False)

# This is only needed when using runserver.
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

diera/archive/models.py
from django.db import models

# Create your models here.

diera/archive/views.py
from urllib.parse import urlparse
from datetime import datetime
import calendar
import pytz

from django.shortcuts import render
from django.http import HttpResponse
from django.core.paginator import Paginator
from django.views.generic.list import ListView
from django.views.generic.base import TemplateView
from django.views.decorators.cache import cache_page

from cms.models import Page

from photologue.models import Gallery
from photologue.models import Photo

from . import queries


class IndexList(ListView):
    template_name = "archive/archive.html"
    paginate_by = 2
    model = Gallery
    context_object_name = "galleries"

    def get_queryset(self):
        return Gallery.objects.filter(is_public__exact=True)


class GalleryList(ListView):
    template_name = "archive/partials/_photo-archive.html"
    paginate_by = 2
    model = Gallery
    context_object_name = "galleries"

    def get_queryset(self):
        year = self.kwargs.get("year")
        month = self.kwargs.get("month")

        # breakpoint()

        if year and month:
            days_in_month = calendar.monthrange(int(year), int(month))[1]
            upper_bound = datetime(int(year), int(month), days_in_month, 23, 59, 59, 999, tzinfo=pytz.UTC)
            lower_bound = datetime(int(year), int(month), 1, 1, 1, 1, 1, tzinfo=pytz.UTC)
            return Gallery.objects.filter(is_public__exact=True).filter(date_added__lte=upper_bound).filter(date_added__gte=lower_bound)
        elif year and not month:
            upper_bound = datetime(int(year), 12, 31, 23, 59, 59, 999999, tzinfo=pytz.UTC)
            lower_bound = datetime(int(year), 1, 1, 1, 1, 1, 1, tzinfo=pytz.UTC)
            return Gallery.objects.filter(is_public__exact=True).filter(date_added__lte=upper_bound).filter(date_added__gte=lower_bound)
        else:
            return Gallery.objects.filter(is_public__exact=True)

class PhotoList(ListView):
    template_name = "archive/partials/_gallery-photos.html"
    paginate_by = 6
    model = Photo
    context_object_name = "gallery_photos"

    def get_queryset(self):
        return Photo.objects.all()

class EventList(ListView):
    template_name = "archive/partials/_programming-archive.html"
    paginate_by = 3
    model = Page
    context_object_name = "events"

    def get_queryset(self):
        # breakpoint()
        return queries.get_all_published_events()

class VideoList(ListView):
    template_name = "archive/partials/_video-archive.html"
    paginate_by = 3
    context_object_name = "videos"

    def get_queryset(self):
        # breakpoint()
        return queries.get_all_yt_videos();

class AudioList(ListView):
    template_name = "archive/partials/_audio-archive.html"
    paginate_by = 3
    context_object_name = "albums"

    def get_queryset(self):
        return queries.get_all_bandcamp_albums()

class SearchResults(TemplateView):
    template_name = "archive/partials/_search-results-masonry.html"
    paginate_by = 6

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # breakpoint()

        if context["page"] == '0':
            context["result_page"] = 0
            return context
        elif context["page"] == '1':
            query = self.request.GET.get("q")
            if not query:
                context["result_page"] = 0
                context["page"] = 0
                return context
            context["query"] = query
        else:
            query = context["query"]

        context["result_page"] = Paginator(queries.query_content(query), self.paginate_by).get_page(context["page"])
        return context

diera/archive/templates/archive/partials/_archive-nav.html
<nav id="archive-nav"
     class="nav-fill"
     :class="(searchInputIsEmpty && !nav) ? 'input-empty' : ''">
    <ul class="nav">
      <li class="nav-item" style="width:56%;" x-show="!nav">
        <input
          id="searchInput"
          hx-trigger="keyup changed delay:500ms"
          hx-target=".swappable"
          hx-swap="outerHTML"
          hx-get="{% url 'archive:search-results' page=1 %}"
          hx-indicator="#init-load-indicator, .search-result"
          name="q"
          x-ref="searchInput"
          x-trap="!nav"
          @keyup="$refs.searchInput.value ? searchInputIsEmpty=false : searchInputIsEmpty=true"
          type="text"
          placeholder="Vyhľadaj v archíve ..."
          class="form-control pe-2 h-100 fs-4"
          aria-label="Search"
        >
      </li>
      <li class="nav-item" x-show="nav">
        <span class="nav-link fs-4"
              style="cursor:pointer"
              aria-current="page"
              hx-get="{% url 'archive:photos' 1 %}"
              hx-target=".swappable"
              hx-swap="outerHTML"
              hx-indicator="#init-load-inicator, .swappable"
              x-on:click="activeCategory='fotky'"
              :class="activeCategory=='fotky' ? 'active' : ''"
        >

          Fotky
        </span>
      </li>
      <li class="nav-item" x-show="nav">
        <span class="nav-link fs-4"
              style="cursor:pointer"
              aria-current="page"
              hx-get="{% url 'archive:programming' 1 %}"
              hx-target=".swappable"
              hx-swap="outerHTML"
              hx-indicator="#init-load-indicator, .swappable"
              x-on:click="activeCategory='program'"
              :class="activeCategory=='program' ? 'active' : ''"
        >
          Program
        </span>
      </li>
      <li class="nav-item" x-show="nav">
        <span class="nav-link fs-4"
              style="cursor:pointer"
              aria-current="page"
              hx-get="{% url 'archive:video' 1 %}"
              hx-target=".swappable"
              hx-swap="outerHTML"
              hx-indicator="#init-load-indicator, .swappable"
              x-on:click="activeCategory='video'"
              :class="activeCategory=='video' ? 'active' : ''"
        >
          Video
        </span>
      </li>
      <li class="nav-item" x-show="nav">
        <span class="nav-link fs-4"
              style="cursor:pointer"
              aria-current="page"
              hx-get="{% url 'archive:audio' 1 %}"
              hx-target=".swappable"
              hx-swap="outerHTML"
              hx-indicator="#init-load-indicator, .swappable"
              x-on:click="activeCategory='audio'"
              :class="activeCategory=='audio' ? 'active' : ''"
        >
          Audio
        </span>
      </li>
      <li class="nav-item" x-show="nav" style="cursor:pointer; width: 10%;" x-on:click="nav=!nav;">
        <span class="nav-link fs-4"
              style="cursor:pointer"
              aria-current="page"
              hx-get="{% url 'archive:search-results' page=0 %}"
              hx-target=".swappable"
              hx-swap="outerHTML"
        >
          <i class="fas fa-search"></i>
        </span>
      </li>
      <li class="nav-item" x-show="!nav" style="cursor:pointer; width: 10px;" x-on:click="nav=!nav;activeCategory='fotky';$refs.searchInput.value=''">
        <span class="nav-link fs-4"
              style="cursor:pointer"
              aria-current="page"
              hx-target=".swappable"
              hx-get="{% url 'archive:photos' page=1 %}"
              hx-swap="outerHTML"
              hx-indicator="#init-load-indicator, .swappable"
        >
          <i class="fas fa-tags"></i>
        </span>
      </li>
    </ul>
</nav>

diera/archive/templates/archive/partials/_audio-archive.html
<div id="audio-archive" class="swappable">
  {% if albums %}
  <div class="row gy-1 gx-1">

    <!-- A page of video teasers -->
    {% for album in albums %}
    {% include "archive/partials/teasers/_audio-teaser.html" %}
    {% endfor %}

    <!-- Infinite scroll -->
    {% if page_obj.has_next %}
    <div hx-target="this"
         hx-trigger="revealed"
         hx-swap="outerHTML"
         hx-select=".feed"
         hx-get="{% url 'archive:audio' page_obj.next_page_number %}"
         class="feed col-12 col-md-6 loading"
         style="border:2px solid black; background-color:white;">
    </div>
    {% endif %}

  </div>
  {% else %}
  There are no albums :(
  {% endif %}

</div>

diera/archive/templates/archive/partials/_date-picker.html
<div class="modal fade" id="dateFilterDialogue" tabindex="-1" aria-labelledby="dateFilterModalDialogue" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="dateFilterModalDialogue">Nastav dátum</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <div id="date-filter"></div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Zavrieť</button>
        <button
          type="button"
          class="btn btn-primary"
          @click="dateFilterIsSet=true;$refs.pickedDateDisplay.innerText=datePicker.format('M / YYYY');URL='/archiv/' + activeCategory + '/' + datePicker.format('YYYY') + '/' + datePicker.format('M') + '/page1/';">
          Uložiť
        </button>
      </div>
    </div>
  </div>
</div>

diera/archive/templates/archive/partials/_event-teaser.html
{% load cms_tags %}
{% load thumbnail %}
{% load archive_tags %}

<div class="feed col-12 col-md-6 col-lg-4">
  <a href="{{ url }}" class="event-teaser">
    <div class="card h-100 p-2 pb-0">
      {% thumbnail image 600x300 crop upscale as teaser_image %}
      <img class="card-img-top" src="{{ teaser_image.url }}">
      <div class="card-body p-0 mt-2">
        <h2 class="card-title fs-1 lh-1 text-uppercase">{{ title }}</h2>
        <h3 class="card-subtitle mt-2 fs-3">
          {% show_placeholder "genre" id %}
        </h3>
      </div>
      <div class="card-footer p-0">
        <div class="row pt-1 pb-1">
          <div class="col-9 fs-3 text-uppercase">{{ date|date:"j.n. / Y" }}</div>
          <div class="col-3 fs-3 text-end">{{ date|date:"H:i" }}</div>
        </div>
      </div>
    </div>
  </a>
</div>

diera/archive/templates/archive/partials/_photo-archive.html
<div id="photo-archive" class="swappable">
  {% if page_obj %}

  <div class="row gx-1 gy-1 mb-1 gallery-page">
    {% for gallery in page_obj %}
    <div class="col-md-6 col-12 gallery-container">
      {% include "archive/partials/teasers/_gallery-teaser.html" %}
    </div>
    {% endfor %}
  </div>

  <!-- Inifinite scroll -->
  {% if page_obj.has_next %}
  <div id="inf-scroll-trigger"
       hx-target="this"
       hx-trigger="revealed"
       hx-swap="outerHTML"
       hx-select=".gallery-page, #inf-scroll-trigger"
       hx-get="{% url 'archive:photos' page_obj.next_page_number %}"
       hx-indicator="#inf-load-indicator"
       class="row gx-1 gy-1">
  </div>
  {% endif %}

  <!-- loading indicators -->
  <div id="inf-load-indicator" class="row mt-1 gx-1 gy-1">
    <div class="p2 col-md-6 col-12">
      <div class="static" style="height:400px;"></div>
    </div>
    <div class="p2 col-md-6 col-12">
      <div class="static" style="height:400px;"></div>
    </div>
  </div>

  {% else %}
  There are no galleries
  {% endif %}
</div>

diera/archive/templates/archive/partials/_programming-archive.html
{% load archive_tags %}
<div id="programming-archive" class="swappable">

  {% if events %}
  <div class="row gx-1 gy-1 mb-1 event-page">

    <!-- A page of events -->
    {% for event in events %}
    {% event_teaser %}
    {% endfor %}

  </div>

  <!-- Infinite scroll -->
  {% if page_obj.has_next %}
  <div
    id="inf-scroll-trigger"
    hx-target="this"
    hx-trigger="revealed"
    hx-swap="outerHTML"
    hx-select=".event-page, #inf-scroll-trigger"
    hx-get="{% url 'archive:programming' page_obj.next_page_number %}"
    hx-indicator="#inf-load-indicator"
    class="row gy-1 gx-1">
  </div>
  {% endif %}

  <!-- loading indicators -->
  <div id="inf-load-indicator" class="row mt-1 gx-1 gy-1">
    <div class="p2 col-md-4 col-12">
      <div class="static"></div>
    </div>
    <div class="p2 col-md-4 col-12">
      <div class="static"></div>
    </div>
    <div class="p2 col-md-4 col-12">
      <div class="static"></div>
    </div>
  </div>

  {% else %}
  There are no events!
  {% endif %}
</div>

diera/archive/templates/archive/partials/_search-results-masonry.html
{% load static %}
<div id="search-results" class="grid swappable">
  {% if result_page == 0 %}
  {% elif result_page %}
  {% for result in result_page %}
  {% include "archive/partials/teasers/_search-result-teaser-masonry.html" %}
  {% endfor %}

  <!-- Infinite scroll -->
  {% if result_page.has_next %}
  <div hx-get="{% url 'archive:search-results' page=result_page.next_page_number query=query %}"
       hx-target="this"
       hx-trigger="revealed"
       hx-swap="outerHTML"
       hx-select=".search-result, .load-trigger"
       hx-indicator=".loading-search"
       class="load-trigger grid-item">
  </div>

  {% endif %}
  {% else %}
  No content satisfy your search criteria :(
  {% endif %}
  <div class="static loading-search grid-item"></div>
  <div class="static loading-search grid-item"></div>
  <div class="static loading-search grid-item"></div>
</div>

{% block js %}
{{ super }}
<script>
/* First init of masonry */
var grid = document.querySelector('.grid');
var msnry = new Masonry( grid, {
  // options
  itemSelector: '.grid-item',
  columnWidth: ".grid-item",
  gutter: 4,
  percentPosition: true
});

// init Masonry after each image loads element
imagesLoaded( document.querySelector('#search-results'), function( instance ) {
  console.log('all images are loaded');
  var grid = document.querySelector('.grid');
  var msnry = new Masonry( grid, {
    // options
    itemSelector: '.grid-item',
    columnWidth: ".grid-item",
    gutter: 4,
    percentPosition: true
  });
});

document.body.addEventListener('htmx:beforeSend', function(evt) {
  console.log("htmx:beforeSend fired");
  var grid = document.querySelector('.grid');
  var msnry = new Masonry( grid, {
    // options
    itemSelector: '.grid-item',
    columnWidth: ".grid-item",
    gutter: 4,
    percentPosition: true
  });
});

/* reinitialized the grid after each reload */
document.body.addEventListener('htmx:load', function(evt) {
  console.log("htmx:load fired!");

  var elem = document.querySelector('.grid');
  var msnry = new Masonry( elem, {
    // options
    itemSelector: '.grid-item',
    columnWidth: ".grid-item",
    gutter: 4,
    percentPosition: true
  });
});
</script>
{% endblock %}

diera/archive/templates/archive/partials/_video-archive.html
<div id="video-archive" class="swappable">

  {% if videos %}
  <div class="row gx-1 gy-1 mt-1 video-page">

    <!-- A page of video teasers -->
    {% for video in videos %}
    {% include "archive/partials/teasers/_video-teaser.html" %}
    {% endfor %}

  </div>

  <!-- Infinite scroll -->
  {% if page_obj.has_next %}
  <div
    id="inf-scroll-trigger"
    hx-target="this"
    hx-trigger="revealed"
    hx-swap="outerHTML"
    hx-select=".video-page, #inf-scroll-trigger"
    hx-get="{% url 'archive:video' page_obj.next_page_number %}"
    hx-indicator="#inf-load-indicator"
    class="row">
  </div>
  {% endif %}

  <!-- loading indicators -->
  <div id="inf-load-indicator" class="row mt-1 gx-1">
    <div class="p2 col-md-4 col-12">
      <div class="static"></div>
    </div>
    <div class="p2 col-md-4 col-12">
      <div class="static"></div>
    </div>
    <div class="p2 col-md-4 col-12">
      <div class="static"></div>
    </div>
  </div>

  {% else %}
  There are no videos :(
  {% endif %}
</div>